name: 'shopify_data_engine'
version: '1.0.0'
config-version: 2
profile: 'shopify_data_engine'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  shopify_data_engine:
    staging:
      +materialized: incremental
      +on_schema_change: sync_all_columns
